htmlbook-xsl/elements.xsl
htmlbook-xsl/epub.xsl
htmlbook-xsl/param.xsl
htmlbook-xsl/xspec/elements.xspec

Added new parameter `footnote.reset.numbering.at.chapter.level`. When enabled (set to 1), then footnote numbering resets to 1 at the beginning of chapter-level elements (elements that are children of `<body>` or Parts: chapter, appendix, preface, etc.). Otherwise footnote numbering does not reset.

New parameter for resetting footnote numbering at chapter level

---

htmlbook-xsl/elements.xsl
htmlbook-xsl/xspec/elements.xspec
htmlbook-xsl/xspec/epub.xspec
htmlbook-xsl/xspec/ncx.xspec
htmlbook-xsl/xspec/opf.xspec

Two fixes for footnote handling:
* When process.footnotes is enabled, nest `<a>` elements in `<sup>` for better results when CSS styling.
* When process.footnotes is disabled, still generate marker numbers for "footnoteref" elements `<a data-type="footnoteref">`

Fixes to footnote handling

---

htmlbook-xsl/chunk.xsl
htmlbook-xsl/elements.xsl
htmlbook-xsl/param.xsl
htmlbook-xsl/xspec/elements.xspec

Added separate handling for table footnotes to HTMLBook stylesheets, largely analogous to handling in DocBook XSL stylesheets (http://docbook.sourceforge.net/release/xsl/current/xhtml-1_1/footnote.xsl): 
* Table footnotes are always placed in `<tfoot>` element at bottom of table, rather than floated to the end of a chunk (as is done when `process.footnotes` is enabled).
* To control numeration style of standard footnotes, use param `footnote.numeration.format`. To control numeration style of table footnotes, use param `table.footnote.numeration.format`. Both take a valid `xsl:number` format-attribute value (e.g., "1", "a").

Table footnote handling

---

htmlbook-xsl/epub.xsl
htmlbook-xsl/opf.xsl
htmlbook-xsl/xspec/opf.xspec

Generalized `embedded.fonts.list` param and  `get.fonts.xml` template to `external.assets.list` param and `get.external.assets.xml`, respectively, to enable their use for both fonts and other external assets (e.g., image assets referenced in CSS url()s)

Generalizing external asset handling for EPUB OPF generation

---

htmlbook-xsl/common.xsl
htmlbook-xsl/elements.xsl
htmlbook-xsl/xspec/common.xspec
htmlbook-xsl/xspec/elements.xspec

Handling to calculate the number of columns in a table, and to add a colspan attribute to `<td>` in table footnotes `<tfoot>`.

Additional <tfoot> handling for table footnotes

---

htmlbook-xsl/tocgen.xsl
htmlbook-xsl/xspec/tocgen.xspec

Added handling so that if you add a class of `notoc` to a `<section>`, e.g.:
````html
<section data-type="sect2" class="notoc">
<h1>Don't show me in TOC</h1>
</section>
````
It will be suppressed from being displayed in the Table of Contents. (Note: this class must appear on the `<section>` and not its child heading element)

Adding handling for "notoc" class to suppress sections from TOC display

---

htmlbook-xsl/ncx.xsl
htmlbook-xsl/tocgen.xsl
htmlbook-xsl/xspec/ncx.xspec
htmlbook-xsl/xspec/tocgen.xspec

Bug fix to ensure that if frontmatter and backmatter that are excluded from TOC generation by default (dedication, copyright page, titlepages, toc, and colophon) contain subsections, these subsections will also be excluded from TOC generation.

Make sure subsections of frontmatter/backmatter are excluded from HTML and NCX TOC generation

---

htmlbook-xsl/common.xsl
htmlbook-xsl/elements.xsl
htmlbook-xsl/xspec/elements.xspec

Adjusted generation of `<tfoot>` elements for table footnotes so that `<tfoot>`s are generated before `<tbody>` or (if no `<tbody>`) the first `<tr>`, rather than at the end of the `<table>`, so that output content model is compatible with both XHTML 1.1 and XHTML5.
Also made `number.of.table.column` handling more robust, accounting for `<th>` as well as `<td>`.

Backward-compatible tfoot generation for table footnotes

---

htmlbook-xsl/elements.xsl
htmlbook-xsl/xspec/elements.xspec

Some legacy ereading engines don't properly float `<tfoot>` content to the bottom of a table, so switching to use `<tbody>` at end of table (or loose `<tr>` if table contains no `<tbody>`) for widest compatibility (even though it's a bit of a shame semantically)

More backward-compatibility adjustments for table footnote generation

---

htmlbook-xsl/epub.xsl
htmlbook-xsl/param.xsl
htmlbook-xsl/tocgen.xsl
htmlbook-xsl/xspec/tocgen.xspec

Added `inline.markup.in.toc` param to allow enabling/disabling inclusion of inline markup tagging (e.g., `em`, `code`) in autogenerated XHTML TOCs.
Set `inline.markup.in.toc` to `0` to drop inline markup tagging from TOC entries, and set `inline.markup.in.toc` to `1` to preserve inline tagging from section headings in TOC entries.
Default behavior is to preserve inline markup tagging in TOC in `param.xsl`, but to disable it in `epub.xsl` (to drop inline markup tagging from EPUB Navigation document, which, while valid EPUB 3, might result in rendering issues in some ereaders).

Added inline.markup.in.toc param

---

htmlbook-xsl/elements.xsl
htmlbook-xsl/xspec/elements.xspec

Added data-footnote-marker attribute to `<span data-type="footnote">` when `process.footnotes` parameter is disabled (i.e., in cases where footnote `<span>`s are postprocessed in place, rather than moved to the end of a section). Results look like this:
````html
<span data-footnote-marker="2" data-type="footnote">Footnote #2 in Chapter #2</span>
````
The data-footnote-marker contains the value of the `footnote.number` template, and can be used by CSS for numbering in cases where it might not be feasible to use `counter()`.

Added data-footnote-marker attribute to footnotes

---

htmlbook-xsl/elements.xsl
htmlbook-xsl/param.xsl
htmlbook-xsl/xspec/elements.xspec

New process.footnote.callouts.only parameter, which lets you generate footnote callout markers, but leave footnote content in place. If you set `process.footnote.callouts` to `1`, then the following footnote markup in source:
````html
<span data-type="footnote">First footnote</span>
````
Will be transformed to the following output:
````html
<sup><a data-type="noteref" id="idm336150198368-marker" href="#idm336150198368">1</a></sup><span data-type="footnote" id="idm336150198368" data-footnote-marker="1">First footnote</span>
````
This makes it possible to autogenerate the "footnote call" markup in place in the body text, while leaving the footnote content in place as well. Potentially useful in conjunction with Paged Media CSS where you want to float the footnote content to the bottom of a …

New process.footnote.callouts.only parameter

---

htmlbook-xsl/xrefgen.xsl
htmlbook-xsl/xspec/xrefgen.xspec
index.html

Added handling for XREFs to refentries (tagged using the markup `<div class="refentry">`. Also added an informative section to HTMLBook spec on refentries.

Handling for XREFs to refentries

---

htmlbook-xsl/chunk.xsl
htmlbook-xsl/common.xsl
htmlbook-xsl/xrefgen.xsl
htmlbook-xsl/xspec/chunk.xspec
htmlbook-xsl/xspec/common.xspec
htmlbook-xsl/xspec/xrefgen.xspec

This PR adds support analogous to that provided in DocBook-XSL for six frequently used XREF styles:
* `select:labelnumber` (print just the label number for the XREF referent, i.e. `template:%n`
* `chap-num-title` (print chapter label and title for XREF chapter referents, i.e. `template:Chapter %n, %t`)
* `select:nopage` (don't add pagenum class to XREF, so page number will be suppressed in paged outputs)
All of the above xrefstyles should be added to a `data-xrefstyle` attribute on the XREF `<a>` element, e.g.:
````html
See Figures <a data-type="xref" data-xrefstyle="select:labelnumber" href="#fig"/> 
and <a data-type="xref" data-xrefstyle="select:labelnumber" href="#fig2"/>
````

Adding support for three frequently used xrefstyles

---

htmlbook-xsl/elements.xsl
htmlbook-xsl/param.xsl
htmlbook-xsl/xspec/elements.xspec

Added handling to toggle on line numbering for code listings, e.g., change the following:
````html
<pre data-type="programlisting" data-line-numbering="numbered">if css_filename
options[:css_filename] ||= css_filename
open(css_filename, "w") {|css_file| css_file.write(result)}
nil
else
result
end</pre>
````
to:
````html
<pre data-type="programlisting" data-line-numbering="numbered"><span class="line-number">1 </span>if css_filename
<span class="line-number">2 </span>  options[:css_filename] ||= css_filename
<span class="line-number">3 </span>  open(css_filename, "w") {|css_file| css_file.write(result)}
<span class="line-number">4 </span>  nil
<span class="line-number">5 </span>else
<span class="line-number">6 </span>  result
<span class="line-number">7 </span>end</pre>
````
Line numbering …

Adding support for code-listing line numbering

---

htmlbook-xsl/xrefgen.xsl
htmlbook-xsl/xspec/xrefgen.xspec

Now checks if the divs class contains "refentry" instead of being equal to it. This prevents refentry divs with other classes from not being matched. Also, adding an extra xspec test for this new behavior.

Updating xref-to behavior for div refentry. 

---

index.html

Fixes mix content warning and unstyled page. 
**`w3.org`** has HTTPS support.
> [![Mix Content warning](http://i.imgur.com/k6Wsr0f.png)](http://i.imgur.com/k6Wsr0f.png)

Use generic url

---

htmlbook-xsl/elements.xsl

Reducing specificity on counting spans with class of "line-number" to work around xsltproc processing bug.

Reducing specificity on counting spans with class of "line-number"

---

htmlbook-xsl/chunk.xsl
htmlbook-xsl/xspec/fileextension.xspec

This PR has two parts:
1. Changing the file extension generated by output-filename-for-chunk to .xhtml
2. Adding fileextension.xspec to test this change
Thanks,
-Nick

ATLAS-27: Update XSL to generate files with .xhtml extension

---

htmlbook-xsl/epub.xsl

This is a change to epub.xsl that sets the filename of the autogenerated cover file to "cover.xhtml". The purpose of this is to avoid epubcheck warnings. See https://intranet.oreilly.com/jira/browse/ATLAS-206

ATLAS-206: Update toolchain to generate EPUB cover file with .xhtml extension

---

htmlbook-xsl/chunk.xsl

This is a change to chunk.xsl that sets the filename of the autogenerated root chunk file to "index.xhtml". The root chunk file is included if there is no titlepage. The purpose of this is to avoid epubcheck warnings as well as to ensure that the Travis CI tests for the Atlas Workers pass as expected. See https://intranet.oreilly.com/jira/browse/ATLAS-206 and https://github.com/oreillymedia/orm-atlas-workers/pull/281

ATLAS-209: Update toolchain to generate index file with .xhtml extension

---

htmlbook-xsl/epub.xsl

Reverts oreillymedia/HTMLBook#225
This has caused unintended consequences on the Platform. Reverting per request from Andrew Odewahn.

Revert "ATLAS-206: Update toolchain to generate EPUB cover file with .xhtml extension"

---

htmlbook-xsl/chunk.xsl

This has caused unintended consequences on the Platform. Reverting per request from Andrew Odewahn.
Reverts oreillymedia/HTMLBook#224

Revert "ATLAS-209: Update toolchain to generate index file with .xhtml extension"

---

htmlbook-xsl/param.xsl
htmlbook-xsl/xrefgen.xsl
htmlbook-xsl/xspec/xrefgen.xspec

NOTE: This seems to work in practice but two xspec tests are not working. Creating a draft PR so I don't forget, but this is not ready for review.
Adding support for cross-references to admonitions (notes, tips, warnings) by
1) Giving them the pagenum class in param.xsl so that xrefs in PDFs display
the page number (as dictated by the CSS theme), and 2) adding handling in
xrefgen.xsl so that a warning is display if the linked admonition has no
title. This is necessary because admonitions are valid with and without
titles.
I branched this off of master and it looks like the staging/master commit history diverged during our last rollback. Not sure what to do about that (if anything). As mentioned above, the relevant files for the diff are param.xsl and xrefgen.xsl.
Priority: Low - Kristen …

TOOLSREQ-6431: Add Support for xrefs to Admonitions 

---

htmlbook-xsl/opf.xsl

When testing whether Amazon will ingest our epubs, we've been
receiving errors that state: "Guide title is empty. Item is ignored"
and "This index is empty and has been skipped". I was able to locate the
source of this error in the content.opf file, which is created by opf.xsl.
In content.opf, there is a <guide> element, which contains <reference>
elements as children. There is a <reference> for the Cover, TOC, and
Title Page. The <reference>s for the Cover and TOC each have 3 attributes:
href, type, and title, while the <reference> for the Title Page only has
the first two.
Looking at the logic within opf.xsl, this seems to be because the Title Page
<reference> is set up to be flexible if there is no Title Page within the
book, and so we didn't want to hardcode a title attribute. …

TOOLSREQ-6840: Adding Title Attribute to <reference> Element in content.opf

---

htmlbook-xsl/opf.xsl

For an unknown reason, the link to the TOC in the <guide> element is causing an error when Amazon attempts to ingest our EPUBs. Rather than remove the <guide> element entirely, we decided to remove just the TOC item to preserve some of the functionality while still allowing us to send EPUBs to Amazon.
Note that this is the same branch as the [previous PR](https://github.com/oreillymedia/HTMLBook/pull/235) so as to make it easier to merge into master when the time comes.

TOOLSREQ-6840: Removing TOC from Guide

---

htmlbook-xsl/opf.xsl
htmlbook-xsl/xspec/opf.xspec

When testing whether Amazon will ingest our epubs, we've been receiving errors that state:
- "Guide title is empty. Item is ignored"
- "This index is empty and has been skipped"
- "Hyperlink not resolved: OEBPS/toc01.html"
- "Some hyperlinks could not be resolved."
I was able to locate the source of these errors in the content.opf file, which is created by opf.xsl. All 4 errors relate to the `<guide>` element, which is created by the `generate-guide` template. The `<guide>` element contains `<reference>` elements as children. There is a `<reference>` for the Cover, TOC, and Title Page. The `<reference>`s for the Cover and TOC each have 3 attributes: href, type, and title, while the `<reference>` for the Title Page only has the first two. The `<guide>` element is an EPUB2 navigation …

TOOLSREQ-6840: Updating opf.xsl to Fix Amazon EPUB Ingestion Errors

---

schema/svg/SVG.xsd

The "version" attribute is specified by SVG[1] and is used by some
libraries like Cairo[2] in their generated SVG output.
Supporting the "version" attribute in the schema allows to validate
files generated by Cairo with xmllint.
[1] https://www.w3.org/TR/SVG11/struct.html#SVGElementVersionAttribute
[2] https://www.cairographics.org/

Add support for the "version" attribute in the SVG schema

---

htmlbook-xsl/localizations/en.xml
htmlbook-xsl/xrefgen.xsl
htmlbook-xsl/xspec/xrefgen.xspec

To better conform with the Chicago Manual of Style, Production has requested we change the way we style the titles generated by cross-references to Appendixes, Chapters, and Parts. Previously they were italicized:
Appendix A, _Example Appendix Title_
Chapter 1, _Example Chapter Title_
Part I, _Example Part Title_
This PR changes them to be normal font surrounding by quotation marks:
Appendix A, “Example Appendix Title”
Chapter 1, “Example Chapter Title”
Part I, “Example Part Title”
There are three files changes, _xrefgen.xsl_ was changed to remove the template that added the italics. _localizations/en.xml_ was changed to add the quotation marks, and _xspec/xrefgen.xspec_ was changed to update a test to match the new format (note that this test is not currently working for other reasons). …

TOOLSREQ-7235: xref-number-and-title Format Change

---

htmlbook-xsl/tocgen.xsl
htmlbook-xsl/xspec/tocgen.xspec

This PR updates the logic of the XSL that generates the TOC to
include the author bio in the TOC. This is done by changing the
line excluding colophons to only exclude colophons if they do not
contain the class abouttheauthor (this is standard for our boilerplate).
It also updates our XSpec testing suite to match the new behavior.
This request comes from Kristen and is based on author complaints of 
how the Author Bio displays on the UCV on the Platform.
https://intranet.oreilly.com/jira/browse/TOOLSREQ-7334
Re-requesting a review because I added the XSpec commit and the time elapsed since the [earlier PR](https://github.com/oreillymedia/HTMLBook/pull/240).

Adding the Author Bio to the TOC

---

index.html
schema/htmlbook.xsd

This commit changes the heading element for sidebars from h5 to h1. This is being done to improve the appearance of content on the Platform.

TOOLSREQ-8313: Changing Sidebar Headers from h5 to h1

---

htmlbook-xsl/opf.xsl

This commit adds a generic template for handling accessibility metadata passed in along with the HTMLBook file such that the following fields are included:
* `accessMode` — a human sensory perceptual system or cognitive faculty necessary to process or perceive the content (e.g., textual, visual, auditory, tactile).
* `accessibilityFeature` — features and adaptations that contribute to the overall accessibility of the content (e.g., alternative text, extended descriptions, captions).
* `accessibilityHazard` — any potential hazards that the content presents (e.g., flashing, motion simulation, sound).
Also included (because it was easy), though not required:
* `accessModeSufficient` – this is what is minimally required to use the ebook
Verified on staging; see PR in `orm-epubrenderer`.

Add handling for required epub accessibility metadata in OPF template
